import IState from './IState'
import ReduxState from './interfaces/ReduxState'
import Comparable from './interfaces/Comparable'
import Step from './interfaces/Step'
import {diffStateToSteps} from '../util/reconciler'
import {serialize, ISerializable} from '../util/serializer'

abstract class Action implements Comparable, ISerializable {
  abstract readonly type: string
  readonly time: number

  constructor({time=new Date().getTime()}:{time?:number}={}) {
    this.time = time
  }

  /**
   * Reducer for this action
   * @param state - The original state
   * @returns {IState} - The new state
   */
  reduce(state:IState):IState {
    return state
  }

  /**
   * Reducer for the store, typically used for just storing this action
   * but can be overridden to do things like clear some or all of the actions
   * @param state - The original state
   * @returns {ReduxState} - The new state
   */
  store(state:ReduxState):ReduxState {
    return {
      actions: [...state.actions, serialize(this)]
    }
  }

  /**
   * Generate steps to run in the browser
   * @param steps - The original steps before this action runs
   * @param state - The original state before this action runs
   * @returns {Step[]} - The original steps plus steps generated by this action
   */
  addSteps(steps:Step[], state:IState):Step[] {
    const newState:IState = this.reduce(state)
    return [...steps, ...diffStateToSteps(state, newState)]
  }

  compareTo(other:Action):number {
    return other.time - this.time
  }
}

export default Action