export const CREATE_CONTAINER = 'create-container'
export const LOAD_FROM_URL = 'load-from-url'
export const SWITCH_TO_CONTAINER = 'switch-to-container'
export const PUSH = 'push'
export const TOP = 'top'
export const BACK = 'back'
export const FORWARD = 'forward'
export const GO = 'go'
export const POPSTATE = 'popstate'

export const SET_ZERO_PAGE = 'set-zero-page'