"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.USER = exports.SYSTEM = exports.ActionOrigin = exports.UserOrigin = exports.SystemOrigin = void 0;
var reconciler_1 = require("../util/reconciler");
var Action_1 = require("../store/Action");
var Serializable_1 = require("../store/decorators/Serializable");
var Action = /** @class */ (function (_super) {
    __extends(Action, _super);
    function Action(_a) {
        var _b = _a === void 0 ? {} : _a, _c = _b.time, time = _c === void 0 ? new Date().getTime() : _c, _d = _b.origin, origin = _d === void 0 ? exports.USER : _d;
        var _this = _super.call(this, { time: time }) || this;
        _this.origin = origin;
        return _this;
    }
    /**
     * Generate steps to run in the browser
     * @param steps - The original steps before this action runs
     * @param state - The original state before this action runs
     * @returns {Step[]} - The original steps plus steps generated by this action
     */
    Action.prototype.addSteps = function (steps, state) {
        var newState = this.reduce(state);
        return __spreadArray(__spreadArray([], steps, true), (0, reconciler_1.diffPagesToSteps)(state.getPages(), newState.getPages()), true);
    };
    return Action;
}(Action_1.default));
var SystemOrigin = /** @class */ (function () {
    function SystemOrigin() {
        this.type = SystemOrigin_1.type;
    }
    SystemOrigin_1 = SystemOrigin;
    var SystemOrigin_1;
    SystemOrigin.type = 'system';
    SystemOrigin = SystemOrigin_1 = __decorate([
        Serializable_1.default
    ], SystemOrigin);
    return SystemOrigin;
}());
exports.SystemOrigin = SystemOrigin;
var UserOrigin = /** @class */ (function () {
    function UserOrigin() {
        this.type = UserOrigin_1.type;
    }
    UserOrigin_1 = UserOrigin;
    var UserOrigin_1;
    UserOrigin.type = 'user';
    UserOrigin = UserOrigin_1 = __decorate([
        Serializable_1.default
    ], UserOrigin);
    return UserOrigin;
}());
exports.UserOrigin = UserOrigin;
var ActionOrigin = /** @class */ (function () {
    function ActionOrigin(action) {
        this.type = ActionOrigin_1.type;
        this.action = action;
    }
    ActionOrigin_1 = ActionOrigin;
    var ActionOrigin_1;
    ActionOrigin.type = 'action';
    ActionOrigin = ActionOrigin_1 = __decorate([
        Serializable_1.default,
        __metadata("design:paramtypes", [Action])
    ], ActionOrigin);
    return ActionOrigin;
}());
exports.ActionOrigin = ActionOrigin;
exports.SYSTEM = new SystemOrigin();
exports.USER = new UserOrigin();
exports.default = Action;
//# sourceMappingURL=Action.js.map