"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
Object.defineProperty(exports, "__esModule", { value: true });
var reconciler_1 = require("../util/reconciler");
var Action_1 = require("../store/Action");
var Serializable_1 = require("../store/decorators/Serializable");
var BaseAction = (function (_super) {
    __extends(BaseAction, _super);
    function BaseAction(_a) {
        var _b = _a === void 0 ? {} : _a, _c = _b.time, time = _c === void 0 ? new Date().getTime() : _c, _d = _b.origin, origin = _d === void 0 ? exports.USER : _d;
        var _this = _super.call(this, { time: time }) || this;
        _this.origin = origin;
        return _this;
    }
    /**
     * Generate steps to run in the browser
     * @param steps - The original steps before this action runs
     * @param state - The original state before this action runs
     * @returns {Step[]} - The original steps plus steps generated by this action
     */
    BaseAction.prototype.addSteps = function (steps, state) {
        var newState = this.reduce(state);
        return steps.concat(reconciler_1.diffPagesToSteps(state.pages, newState.pages));
    };
    return BaseAction;
}(Action_1.default));
var SystemOrigin = SystemOrigin_1 = (function () {
    function SystemOrigin() {
        this.type = SystemOrigin_1.type;
    }
    return SystemOrigin;
}());
SystemOrigin.type = 'system';
SystemOrigin = SystemOrigin_1 = __decorate([
    Serializable_1.default
], SystemOrigin);
exports.SystemOrigin = SystemOrigin;
var UserOrigin = UserOrigin_1 = (function () {
    function UserOrigin() {
        this.type = UserOrigin_1.type;
    }
    return UserOrigin;
}());
UserOrigin.type = 'user';
UserOrigin = UserOrigin_1 = __decorate([
    Serializable_1.default
], UserOrigin);
exports.UserOrigin = UserOrigin;
var ActionOrigin = ActionOrigin_1 = (function () {
    function ActionOrigin(action) {
        this.type = ActionOrigin_1.type;
        this.action = action;
    }
    return ActionOrigin;
}());
ActionOrigin.type = 'action';
ActionOrigin = ActionOrigin_1 = __decorate([
    Serializable_1.default,
    __metadata("design:paramtypes", [BaseAction])
], ActionOrigin);
exports.ActionOrigin = ActionOrigin;
exports.SYSTEM = new SystemOrigin();
exports.USER = new UserOrigin();
exports.default = BaseAction;
var SystemOrigin_1, UserOrigin_1, ActionOrigin_1;
//# sourceMappingURL=BaseAction.js.map